CREATE TABLE foods (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       category VARCHAR(255) NOT NULL,
                       description TEXT,
                       name VARCHAR(255) NOT NULL
);

CREATE TABLE food_safety (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             notes TEXT,
                             risk_level VARCHAR(255) NOT NULL,
                             species VARCHAR(255) NOT NULL,
                             verified_by BIGINT,
                             verified_status VARCHAR(255) NOT NULL,
                             food_id BIGINT NOT NULL,
                             life_stage VARCHAR(255),
                             CONSTRAINT food_safety_life_stage_check CHECK (life_stage IN ('PUPPY', 'ADULT', 'SENIOR')),
                             CONSTRAINT food_safety_risk_level_check CHECK (risk_level IN ('SAFE', 'MODERATE', 'TOXIC', 'LETHAL')),
                             CONSTRAINT food_safety_verified_status_check CHECK (verified_status IN ('PENDING', 'VERIFIED')),
                             CONSTRAINT uk_food_safety_food_species_stage UNIQUE (food_id, species, life_stage),
                             CONSTRAINT fk_food_safety_food FOREIGN KEY (food_id) REFERENCES foods(id)
);

CREATE TABLE sources (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         source_name VARCHAR(255) NOT NULL,
                         source_url VARCHAR(255),
                         food_safety_id BIGINT NOT NULL,
                         CONSTRAINT fk_sources_food_safety FOREIGN KEY (food_safety_id) REFERENCES food_safety(id)
);

CREATE TABLE faqs (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      answer TEXT,
                      answered_at TIMESTAMP(6),
                      answered_by BIGINT,
                      asked_by BIGINT NOT NULL,
                      created_at TIMESTAMP(6) NOT NULL,
                      question TEXT NOT NULL,
                      status VARCHAR(255) NOT NULL,
                      CONSTRAINT faqs_status_check CHECK (status IN ('PENDING', 'ANSWERED'))
);

CREATE TABLE emergency_guides (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  emergency_contacts_info TEXT,
                                  risk_level VARCHAR(255) NOT NULL UNIQUE,
                                  steps TEXT NOT NULL,
                                  CONSTRAINT emergency_guides_risk_level_check CHECK (risk_level IN ('SAFE', 'MODERATE', 'TOXIC', 'LETHAL'))
);