spring:
  application:
    name: food-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${FOOD_SERVICE_DB:canmypet_foods}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: ${FOOD_SERVICE_PORT:8083}

jwt:
  secret: ${JWT_SECRET}

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}