CREATE TABLE pets (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      birth_date DATE,
                      breed VARCHAR(255),
                      medical_conditions TEXT,
                      name VARCHAR(255) NOT NULL,
                      owner_id BIGINT NOT NULL,
                      species VARCHAR(255) NOT NULL,
                      weight NUMERIC(38, 2),
                      life_stage VARCHAR(255),
                      CONSTRAINT pets_life_stage_check CHECK (life_stage IN ('PUPPY', 'ADULT', 'SENIOR'))
);

CREATE TABLE search_history (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                food_id BIGINT NOT NULL,
                                searched_at TIMESTAMP(6) NOT NULL,
                                user_id BIGINT NOT NULL,
                                pet_id BIGINT,
                                CONSTRAINT fk_search_history_pet FOREIGN KEY (pet_id) REFERENCES pets(id)
);