CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP(6) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       license_number VARCHAR(255),
                       name VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(255) NOT NULL,
                       verified BOOLEAN NOT NULL,
                       CONSTRAINT users_role_check CHECK (role IN ('OWNER', 'VETERINARIAN', 'ADMIN'))
);